# Используем официальный образ Nginx
FROM nginx:latest

# Копируем наши конфигурационные файлы Nginx
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./ssl /etc/nginx/ssl

# Указываем рабочую директорию
WORKDIR /etc/nginx
